title:  مبینااسمعیل پور
logo: /assets/img/logo.png
email: esmaeilpour.mm
description: I'm a student of Computer Engineering at IUST.
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
